wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.23
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.2
    t:
      1:
      - 1
      2:
      - 1
      4: 3.9.2
      5: 0.10.23
      8:
      - 5
adam:
  desc: null
  value: false
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 40
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: true
cfg:
  desc: null
  value: ./models/yolov5s.yaml
data:
  desc: null
  value: ./data/data.yaml
data_dict:
  desc: null
  value:
    names:
    - Sittichoke
    - TyreForYou
    - ThaiCharoen_Rubber
    - ThaiCharoen_Service
    - SamThaiTruck
    - SamThaiTruck_Service
    - DeDay_TruckTire_Center
    - RoongThai
    - ChaiChod_RuamYang
    - SriRaCha
    - KrabiYangThong
    - SaGuan
    - SaGuan_Chumphorn
    - ThaiRat
    - BTC
    - PY
    - CHER
    - SamRan_Chaiyaphum
    - Ubon_LoYang
    - TyreMart
    - SaHai
    - GiantTyre
    nc: 22
    test: ./data/images/test/
    train: ./data/images/train/
    val: ./data/images/val/
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 300
evolve:
  desc: null
  value: false
exist_ok:
  desc: null
  value: false
global_rank:
  desc: null
  value: -1
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.2
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
img_size:
  desc: null
  value:
  - 416
  - 416
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: invocr
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: true
notest:
  desc: null
  value: false
opt:
  desc: null
  value:
    adam: false
    artifact_alias: latest
    batch_size: 40
    bbox_interval: -1
    bucket: ''
    cache_images: true
    cfg: ./models/yolov5s.yaml
    data: ./data/data.yaml
    device: ''
    entity: null
    epochs: 300
    evolve: false
    exist_ok: false
    global_rank: -1
    hyp:
      anchor_t: 4.0
      box: 0.05
      cls: 0.5
      cls_pw: 1.0
      degrees: 0.0
      fl_gamma: 0.0
      fliplr: 0.5
      flipud: 0.0
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      iou_t: 0.2
      lr0: 0.01
      lrf: 0.2
      mixup: 0.0
      momentum: 0.937
      mosaic: 1.0
      obj: 1.0
      obj_pw: 1.0
      perspective: 0.0
      scale: 0.5
      shear: 0.0
      translate: 0.1
      warmup_bias_lr: 0.1
      warmup_epochs: 3.0
      warmup_momentum: 0.8
      weight_decay: 0.0005
    image_weights: false
    img_size:
    - 416
    - 416
    linear_lr: false
    local_rank: -1
    multi_scale: false
    name: invocr
    noautoanchor: false
    nosave: true
    notest: false
    project: runs/train
    quad: false
    rect: false
    resume: false
    save_dir: runs/train/invocr
    save_period: -1
    single_cls: false
    sync_bn: false
    total_batch_size: 40
    upload_dataset: false
    weights: ./weights/yolov5s.pt
    workers: 8
    world_size: 1
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/invocr
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
total_batch_size:
  desc: null
  value: 40
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: ./weights/yolov5s.pt
workers:
  desc: null
  value: 8
world_size:
  desc: null
  value: 1
